server:
  port: 80
  servlet:
    session:
      timeout: 600
      cookie:
        http-only: true
        secure: false

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
#  freemarker:
#    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
#    suffix: .html # 模版后缀名 默认为ftl
#    charset: UTF-8 # 文件编码
#    template-loader-path: classpath:/templates/

#logging:
#    config: classpath:log4j2-dev.xml

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

raven:
  security:
    browser:
      signUpUrl: /demo-signUp.html
      #      loginPage: /demo-login.html
      loginType: JSON
    validate:
      image:
        count: 3
        width: 100
        validateUrls:
          - /syslog
      mobile:
        count: 4
    social:
      filterProcessesUrl: /qqLogin
      qq:
        appId: 100550231
        appSecret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      wx:
        appId: wxd99431bbff8305a0
        appSecret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin

security:
  oauth2:
    client:
      client-id: RavenId
      client-secret: RavenSecret
